### ISSUE TITLE
Not an issue, just a thanks.

### ISSUE THREAD

**Issue by geuis** [voidqk/polybooljs#11]
Thanks for writing this library. I needed to union a lot of geojson geometries together and it made no sense to import the entire jsts library for one utility. With yours coming in at roughly 21kb compared to over 400kb for jsts, its a huge improvement. So far haven't encountered any polygon <-> geojson problems but I'll report back if something happens.

**Comment by voidqk** [comment]
Awesome, glad it helped!  Happy to give back to open-source in whatever small way I can :-).

**Comment by greeny1000** [comment]
I just wanted to add my thanks too.
Not only for the library, but also for the great tutorial on your website.
http://sean.cm/a/polygon-clipping-pt2
Cheers
