### ISSUE TITLE
How to separate poly to several polys

### ISSUE THREAD

**Issue by huangdade** [voidqk/polybooljs#15]
After some bool operations, I may get a poly which actual is a combination of several separated polys, like this:

![image](https://user-images.githubusercontent.com/4537048/57217486-50033880-7025-11e9-8fbd-c374cb204597.png)

this blue poly difference the red poly and get the green poly.

How could I separate the green poly to two polys? Is there a simple solution to this question, or I need to solve it by other algorithm?

**Comment by voidqk** [comment]
The result's `regions` is a list of polygons, so simply index into it.

**Comment by huangdade** [comment]
What if the result contains holes? like this:

![image](https://user-images.githubusercontent.com/4537048/57226864-8a2f0300-7042-11e9-8b9b-a6a76507d257.png)

I want to separate them to A and B.

**Comment by voidqk** [comment]
Hmm, that's a good question.

But I think it's outside the scope of this library.

You might be able to use some of the logic that's in `geojson.js` to figure out the different roots:

https://github.com/voidqk/polybooljs/blob/master/lib/geojson.js#L52

There's a comment describing a similar issue.

**Comment by huangdade** [comment]
So the index of each polygon does not tell anything about their spatial relationship, right?

**Comment by voidqk** [comment]
correct

**Comment by huangdade** [comment]
I get it.
