### ISSUE TITLE
Support for polygon with holes?

### ISSUE THREAD

**Issue by bluenote10** [voidqk/polybooljs#18]
I'm wondering if this library can support polygon with holes? I'm not sure what the `inverted` property of a polygon is supposed to mean. My guess was that it is used to handle what is commonly called polygon holes. However when taking the union of these 4 "border" rectangles

![debug_polys_input](https://user-images.githubusercontent.com/3620703/71771511-6fe45680-2f3c-11ea-9def-eaab1d96ad37.png)

using

```js
var PolyBool = require('polybooljs');

let polygons = [
  {"regions":[[[0,0],[100,0],[100,10],[0,10]]],"inverted":false},
  {"regions":[[[90,0],[100,0],[100,100],[90,100]]],"inverted":false},
  {"regions":[[[0,90],[100,90],[100,100],[0,100]]],"inverted":false},
  {"regions":[[[0,0],[10,0],[10,100],[0,100]]],"inverted":false},
]

// Using the naive multi polygon join. The approach via segments seems to give the same results.
var union = polygons[0];
for (var i = 1; i < polygons.length; i++) {
  union = PolyBool.union(union, polygons[i]);
}

console.log(JSON.stringify(union));
```

This should produce a single polygon (the outer ring) with one hole (the inner ring). However, I'm getting a polygon with two regions, and there is no way to differentiate what is exterior / interior from the output:

```
{"regions":[[[90,90],[90,10],[10,10],[10,90]],[[100,100],[100,0],[0,0],[0,100]]],"inverted":false}
```
Graphically:
![debug_polys_output_polybooljs](https://user-images.githubusercontent.com/3620703/71771531-d9646500-2f3c-11ea-96e0-7cadc5e414f5.png)

Is there a way to properly determine polygon holes?

**Comment by voidqk** [comment]
Yes, polybooljs thinks of holes as according to the even-odd rule:

https://en.wikipedia.org/wiki/Even%E2%80%93odd_rule

The demo is probably the quickest way to see how the `inverted` flag works (by clicking on Invert Red and Invert Blue buttons):

https://rawgit.com/voidqk/polybooljs/master/dist/demo.html

The GeoJSON conversion will translate from even-odd to vertex winding (either clockwise is a hole, or counter-clockwise, I forget which).
