### ISSUE TITLE
Polygon union of rectangles produces inconsistent result

### ISSUE THREAD

**Issue by mazznoer** [voidqk/polybooljs#19]
```js
let rects = [
	[ // rect 1
		[10,10],
		[20,10],
		[20,20],
		[10,20],
	],[ // rect 2
		[20,20],
		[30,20],
		[30,30],
		[20,30],
	],[ // rect 3
		[10,30],
		[20,30],
		[20,40],
		[10,40],
	],
];

let poly = PolyBool.union({
	regions: rects,
	inverted: false,
}, {
	regions: [],
	inverted: false,
});
```
![svgx-1578646604](https://user-images.githubusercontent.com/56464409/72140373-30e25500-33c3-11ea-8fd1-6c784ee4e512.png)

Why rect 1 and rect 2 is not merged, but rect 2 and rect 3 is merged?

Is there any way to disable this corner to corner union?

Sorry for my broken english.

**Comment by voidqk** [comment]
Sorry for the late reply, I don't check here very often anymore.

To answer your question: the library does not make promises about how the final object is built, other than it will be the correct boolean result.  It could have just as easily created _three_ regions.

The result is correct, as far as the library is concerned.  If you want to do further simplification by attempting to combine regions, then that's outside the scope of this library.
