### ISSUE TITLE
Performance benchmarks

### ISSUE THREAD

**Issue by xaviergonz** [voidqk/polybooljs#5]
Are there any performance benchmarks vs other libs available? 

JsClipper, the javascript port of Angus Johnsons Clipper (based on Vatti´s algorithm) come to mind for example

**Comment by voidqk** [comment]
No, there aren't.  I would gladly put performance information in the README if someone provided it to me, and it was compared fairly with other libraries.

**Comment by xaviergonz** [comment]
What would constitute a fair comparison?

**Comment by voidqk** [comment]
I don't know, that's a good question.  That's part of the problem of reporting on performance.  I suppose it would depend on the features of the other library, and the expected use cases.  Do you plan on trying to perform a fair comparison?

**Comment by voidqk** [comment]
Closing for now.
