### ISSUE TITLE
PolyBool.combine modifies its arguments

### ISSUE THREAD

**Issue by manubb** [voidqk/polybooljs#6]
If you consider 3 polygons p1, p2 and p3. The following operations produce unespected result:
```js
var s1 = PolyBool.segments(p1);
var s2 = PolyBool.segments(p2);
var s3 = PolyBool.segments(p3);
var comb1 = PolyBool.combine(s1, s2); //this modifies s1 and s2
var res1 = PolyBool.polygon(Polybool.selectUnion(comb1));
var comb2 = PolyBool.combine(s1, s3); //bad since s1 has been modified
var res2 = PolyBool.polygon(Polybool.selectUnion(comb2));
```
It appears that the result of a PolyBool.segments call can only be used once. Do you think that this could be fixed? (If not, i suggest to mention this in the documentation.)

**Comment by voidqk** [comment]
Good catch, thanks!

I just pushed a fix, can you pull it and see if it works as expected for you?  If so, I'll cut a new version.

**Comment by manubb** [comment]
Yes, the issue seems to be fixed with your last commit. Thanks for your support and your nice lib.

**Comment by voidqk** [comment]
Awesome, you're welcome!  Thanks for the report.  I'll push out a new version here shortly.
